# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0003_register_model_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
