# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-25 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
