# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0004_register_model_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
