# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_model', '0005_register_model_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('service_area', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=200)),
                ('pin', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='register_model',
            old_name='email_confirmed',
            new_name='email_verified',
        ),
        migrations.RemoveField(
            model_name='register_model',
            name='verified',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_model.register_model'),
        ),
    ]
