# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190201_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('lastupdated', models.DateTimeField(auto_now=True)),
                ('Productt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product_price',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
