# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190202_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_discount',
            old_name='Productt',
            new_name='product',
        ),
    ]
