# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190202_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_discount',
            name='Offer',
            field=models.IntegerField(default=0.0),
        ),
    ]
