# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190202_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_price_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list_date', models.DateField(auto_now_add=True)),
                ('price_list_time', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.CharField(default=101, max_length=30)),
                ('offer_price', models.FloatField(default=10.5)),
                ('list_price', models.IntegerField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('total_available_quantity', models.FloatField(default=50.5)),
                ('rating', models.IntegerField(default=2.5)),
                ('Total', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
