# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_daily_price_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_price_list',
            name='Total',
        ),
    ]
